Praticando tensores

In [1]:
import torch

Configurando a GPU como dispositivo padrão

In [ ]:
device = torch.device('cuda:0')
torch.set_default_device(device)

device(type='cuda', index=0)

Operações básicas

In [57]:
zeros_float = torch.zeros(4, 4, dtype=torch.float64)
zeros_float

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], device='cuda:0', dtype=torch.float64)

In [12]:
zeros_int = torch.zeros(4, 4, dtype=torch.int64)
zeros_int

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]], device='cuda:0')

In [13]:
ones = torch.ones(3, 3, dtype=torch.int)
ones

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], device='cuda:0', dtype=torch.int32)

In [25]:
random = torch.rand(3, 3)
random

tensor([[0.4435, 0.4703, 0.3976],
        [0.4462, 0.2084, 0.7574],
        [0.4054, 0.5099, 0.4331]], device='cuda:0')

Somando, subtraindo, dividindo, multiplicando e extraindo o resto da divisão

In [26]:
random + ones

tensor([[1.4435, 1.4703, 1.3976],
        [1.4462, 1.2084, 1.7574],
        [1.4054, 1.5099, 1.4331]], device='cuda:0')

In [28]:
random - ones

tensor([[-0.5565, -0.5297, -0.6024],
        [-0.5538, -0.7916, -0.2426],
        [-0.5946, -0.4901, -0.5669]], device='cuda:0')

In [30]:
random / 2

tensor([[0.2218, 0.2351, 0.1988],
        [0.2231, 0.1042, 0.3787],
        [0.2027, 0.2549, 0.2165]], device='cuda:0')

In [31]:
random * 2

tensor([[0.8870, 0.9406, 0.7952],
        [0.8924, 0.4168, 1.5147],
        [0.8108, 1.0197, 0.8662]], device='cuda:0')

In [35]:
random % 0.1

tensor([[0.0435, 0.0703, 0.0976],
        [0.0462, 0.0084, 0.0574],
        [0.0054, 0.0099, 0.0331]], device='cuda:0')

In [38]:
torch.det(random)

tensor(-0.0209, device='cuda:0')

In [45]:
torch.svd(random)

torch.return_types.svd(
U=tensor([[-0.5418,  0.4365, -0.7182],
        [-0.6281, -0.7781,  0.0009],
        [-0.5584,  0.4517,  0.6958]], device='cuda:0'),
S=tensor([1.3704, 0.3523, 0.0432], device='cuda:0'),
V=tensor([[-0.5451,  0.0839, -0.8342],
        [-0.4892,  0.7762,  0.3977],
        [-0.6808, -0.6249,  0.3821]], device='cuda:0'))

In [53]:
torch.std_mean(random)

(tensor(0.1422, device='cuda:0'), tensor(0.4524, device='cuda:0'))